versionLookupArtifact=mqtt-client
kotlin.code.style=official
android.useAndroidX=true
org.gradle.jvmargs=-XX:MaxMetaspaceSize=4g
org.gradle.parallel=true
org.gradle.caching=true
kotlin.mpp.stability.nowarn=true
publishedGroupId=com.ditchoom
siteUrl=https://github.com/DitchOoM/mqtt
gitUrl=git://github.com/DitchOOM/mqtt.git
developerId=thebehera
developerOrg=Ditchoom
developerName=Rahul Behera
developerEmail=rbehera@gmail.com
licenseName=MIT License
licenseUrl=https://opensource.org/licenses/MIT
allLicenses=["MIT"]
