name: "Build Test and Deploy"
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '19'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_SIGNING_PASSWORD }}
      - run: "${GITHUB_WORKSPACE}/.github/mosquitto/mosquitto-osx.sh"
      - name: Test and deploy with Gradle
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: ./gradlew publishAllPublicationsToSonatypeRepository publish
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs