name: "Build and Test"
on:
  pull_request:
    paths-ignore:
      - '*.md'
    types:
      - synchronize
      - opened
jobs:
  review:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '19'
          cache: gradle
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Tests with Gradle Major
        if:  ${{ contains(github.event.pull_request.labels.*.name, 'major') }}
        run: ./gradlew startAutobahnDockerContainer ktlintCheck assemble build check allTests publishToMavenLocal -PincrementMajor=true
      - name: Tests with Gradle Minor
        if:  ${{ contains(github.event.pull_request.labels.*.name, 'minor') }}
        run: ./gradlew startAutobahnDockerContainer ktlintCheck assemble build check allTests publishToMavenLocal -PincrementMinor=true
      - name: Tests with Gradle Patch
        if:  ${{ !contains(github.event.pull_request.labels.*.name, 'major') && !contains(github.event.pull_request.labels.*.name, 'minor') }}
        run: ./gradlew startAutobahnDockerContainer ktlintCheck assemble build check allTests publishToMavenLocal