name: "Build and Test"
on:
  pull_request:
    paths-ignore:
      - '*.md'
    types:
      - synchronize
      - opened

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux.yaml

  build-apple:
    uses: ./.github/workflows/build-apple.yaml

  validate:
    needs: [build-linux, build-apple]
    uses: ./.github/workflows/validate-artifacts.yaml
    with:
      version: ${{ needs.build-linux.outputs.version }}
